name: Pipeline de Integração Contínua (CI)

on: [push]

jobs:
  testes:
    runs-on: self-hosted
    
    steps:
      - name: Baixar Código
        uses: actions/checkout@v4

      - name: Instalar Dependências
        run: npm install

      - name: Executar Testes Automatizados e Gerar Relatório
        run: npm test
